SELECT P.PRODUCT_CODE, (P.PRICE * S.AMT) AS SALES FROM PRODUCT P
JOIN (SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS AMT FROM OFFLINE_SALE GROUP BY PRODUCT_ID) S
ON P.PRODUCT_ID = S.PRODUCT_ID
ORDER BY SALES DESC, P.PRODUCT_CODE ASC;
-- 코드를 입력하세요
-- SELECT P.PRODUCT_CODE, SUM(P.PRICE * S.SALES_AMOUNT) AS TOTAL_SALES
-- FROM PRODUCT P
-- JOIN OFFLINE_SALE S ON P.PRODUCT_ID = S.PRODUCT_ID
-- GROUP BY P.PRODUCT_CODE
-- ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID ASC;